# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_image_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 604, 581))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fittoscreen_button = QtWidgets.QPushButton(self.centralwidget)
        self.fittoscreen_button.setMinimumSize(QtCore.QSize(100, 0))
        self.fittoscreen_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.fittoscreen_button.setObjectName("fittoscreen_button")
        self.horizontalLayout.addWidget(self.fittoscreen_button)
        self.zoomin_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoomin_button.setMinimumSize(QtCore.QSize(100, 0))
        self.zoomin_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zoomin_button.setObjectName("zoomin_button")
        self.horizontalLayout.addWidget(self.zoomin_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 21))
        self.menubar.setObjectName("menubar")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuR = QtWidgets.QMenu(self.menuImage)
        self.menuR.setObjectName("menuR")
        self.menuG = QtWidgets.QMenu(self.menuImage)
        self.menuG.setObjectName("menuG")
        self.menuB = QtWidgets.QMenu(self.menuImage)
        self.menuB.setObjectName("menuB")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExtent = QtWidgets.QMenu(self.menubar)
        self.menuExtent.setObjectName("menuExtent")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBand_1 = QtWidgets.QAction(MainWindow)
        self.actionBand_1.setCheckable(True)
        self.actionBand_1.setObjectName("actionBand_1")
        self.actionBand_2 = QtWidgets.QAction(MainWindow)
        self.actionBand_2.setCheckable(True)
        self.actionBand_2.setObjectName("actionBand_2")
        self.actionBand_3 = QtWidgets.QAction(MainWindow)
        self.actionBand_3.setCheckable(True)
        self.actionBand_3.setObjectName("actionBand_3")
        self.actionBand_4 = QtWidgets.QAction(MainWindow)
        self.actionBand_4.setCheckable(True)
        self.actionBand_4.setObjectName("actionBand_4")
        self.actionBand_5 = QtWidgets.QAction(MainWindow)
        self.actionBand_5.setCheckable(True)
        self.actionBand_5.setObjectName("actionBand_5")
        self.actionBand_6 = QtWidgets.QAction(MainWindow)
        self.actionBand_6.setCheckable(True)
        self.actionBand_6.setObjectName("actionBand_6")
        self.actionBand_7 = QtWidgets.QAction(MainWindow)
        self.actionBand_7.setCheckable(True)
        self.actionBand_7.setObjectName("actionBand_7")
        self.actionBand_8 = QtWidgets.QAction(MainWindow)
        self.actionBand_8.setCheckable(True)
        self.actionBand_8.setObjectName("actionBand_8")
        self.actionBand_9 = QtWidgets.QAction(MainWindow)
        self.actionBand_9.setCheckable(True)
        self.actionBand_9.setObjectName("actionBand_9")
        self.actionBand_10 = QtWidgets.QAction(MainWindow)
        self.actionBand_10.setCheckable(True)
        self.actionBand_10.setObjectName("actionBand_10")
        self.actionBand_11 = QtWidgets.QAction(MainWindow)
        self.actionBand_11.setCheckable(True)
        self.actionBand_11.setObjectName("actionBand_11")
        self.actionBand_12 = QtWidgets.QAction(MainWindow)
        self.actionBand_12.setCheckable(True)
        self.actionBand_12.setObjectName("actionBand_12")
        self.actionBand_13 = QtWidgets.QAction(MainWindow)
        self.actionBand_13.setCheckable(True)
        self.actionBand_13.setObjectName("actionBand_13")
        self.actionBand_14 = QtWidgets.QAction(MainWindow)
        self.actionBand_14.setCheckable(True)
        self.actionBand_14.setObjectName("actionBand_14")
        self.actionBand_15 = QtWidgets.QAction(MainWindow)
        self.actionBand_15.setCheckable(True)
        self.actionBand_15.setObjectName("actionBand_15")
        self.actionBand_16 = QtWidgets.QAction(MainWindow)
        self.actionBand_16.setCheckable(True)
        self.actionBand_16.setObjectName("actionBand_16")
        self.actionBand_17 = QtWidgets.QAction(MainWindow)
        self.actionBand_17.setCheckable(True)
        self.actionBand_17.setObjectName("actionBand_17")
        self.actionBand_18 = QtWidgets.QAction(MainWindow)
        self.actionBand_18.setCheckable(True)
        self.actionBand_18.setObjectName("actionBand_18")
        self.actionNDVI = QtWidgets.QAction(MainWindow)
        self.actionNDVI.setObjectName("actionNDVI")
        self.action100x100 = QtWidgets.QAction(MainWindow)
        self.action100x100.setCheckable(True)
        self.action100x100.setObjectName("action100x100")
        self.action250x250 = QtWidgets.QAction(MainWindow)
        self.action250x250.setCheckable(True)
        self.action250x250.setObjectName("action250x250")
        self.action500x500 = QtWidgets.QAction(MainWindow)
        self.action500x500.setCheckable(True)
        self.action500x500.setObjectName("action500x500")
        self.action1000x1000 = QtWidgets.QAction(MainWindow)
        self.action1000x1000.setCheckable(True)
        self.action1000x1000.setObjectName("action1000x1000")
        self.actionFull = QtWidgets.QAction(MainWindow)
        self.actionFull.setCheckable(True)
        self.actionFull.setObjectName("actionFull")
        self.actionUpdateBands = QtWidgets.QAction(MainWindow)
        self.actionUpdateBands.setObjectName("actionUpdateBands")
        self.menuR.addAction(self.actionBand_1)
        self.menuR.addAction(self.actionBand_2)
        self.menuR.addAction(self.actionBand_3)
        self.menuR.addAction(self.actionBand_4)
        self.menuR.addAction(self.actionBand_5)
        self.menuR.addAction(self.actionBand_6)
        self.menuG.addAction(self.actionBand_7)
        self.menuG.addAction(self.actionBand_8)
        self.menuG.addAction(self.actionBand_9)
        self.menuG.addAction(self.actionBand_10)
        self.menuG.addAction(self.actionBand_11)
        self.menuG.addAction(self.actionBand_12)
        self.menuB.addAction(self.actionBand_13)
        self.menuB.addAction(self.actionBand_14)
        self.menuB.addAction(self.actionBand_15)
        self.menuB.addAction(self.actionBand_16)
        self.menuB.addAction(self.actionBand_17)
        self.menuB.addAction(self.actionBand_18)
        self.menuImage.addAction(self.menuR.menuAction())
        self.menuImage.addAction(self.menuG.menuAction())
        self.menuImage.addAction(self.menuB.menuAction())
        self.menuImage.addAction(self.actionUpdateBands)
        self.menuExtent.addAction(self.action100x100)
        self.menuExtent.addAction(self.action250x250)
        self.menuExtent.addAction(self.action500x500)
        self.menuExtent.addAction(self.action1000x1000)
        self.menuExtent.addAction(self.actionFull)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuExtent.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fittoscreen_button.setText(_translate("MainWindow", "FitToScreen"))
        self.zoomin_button.setText(_translate("MainWindow", "Zoom In"))
        self.menuImage.setTitle(_translate("MainWindow", "Bands"))
        self.menuR.setTitle(_translate("MainWindow", "R"))
        self.menuG.setTitle(_translate("MainWindow", "G"))
        self.menuB.setTitle(_translate("MainWindow", "B"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExtent.setTitle(_translate("MainWindow", "Extent"))
        self.actionBand_1.setText(_translate("MainWindow", "Band 1"))
        self.actionBand_2.setText(_translate("MainWindow", "Band 2"))
        self.actionBand_3.setText(_translate("MainWindow", "Band 3"))
        self.actionBand_4.setText(_translate("MainWindow", "Band 4"))
        self.actionBand_5.setText(_translate("MainWindow", "Band 5"))
        self.actionBand_6.setText(_translate("MainWindow", "Band 6"))
        self.actionBand_7.setText(_translate("MainWindow", "Band 1"))
        self.actionBand_8.setText(_translate("MainWindow", "Band 2"))
        self.actionBand_9.setText(_translate("MainWindow", "Band 3"))
        self.actionBand_10.setText(_translate("MainWindow", "Band 4"))
        self.actionBand_11.setText(_translate("MainWindow", "Band 5"))
        self.actionBand_12.setText(_translate("MainWindow", "Band 6"))
        self.actionBand_13.setText(_translate("MainWindow", "Band 1"))
        self.actionBand_14.setText(_translate("MainWindow", "Band 2"))
        self.actionBand_15.setText(_translate("MainWindow", "Band 3"))
        self.actionBand_16.setText(_translate("MainWindow", "Band 4"))
        self.actionBand_17.setText(_translate("MainWindow", "Band 5"))
        self.actionBand_18.setText(_translate("MainWindow", "Band 6"))
        self.actionNDVI.setText(_translate("MainWindow", "NDVI"))
        self.action100x100.setText(_translate("MainWindow", "100x100"))
        self.action250x250.setText(_translate("MainWindow", "250x250"))
        self.action500x500.setText(_translate("MainWindow", "500x500"))
        self.action1000x1000.setText(_translate("MainWindow", "1000x1000"))
        self.actionFull.setText(_translate("MainWindow", "Full"))
        self.actionUpdateBands.setText(_translate("MainWindow", "Update"))

