# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MAIN.UI'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TAP_Tool(object):
    def setupUi(self, TAP_Tool):
        TAP_Tool.setObjectName("LCMAP_TAP")
        TAP_Tool.resize(879, 444)
        TAP_Tool.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(TAP_Tool)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_main = QtWidgets.QGridLayout()
        self.gridLayout_main.setObjectName("gridLayout_main")
        spacerItem = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_main.addItem(spacerItem, 13, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotbutton = QtWidgets.QPushButton(self.centralwidget)
        self.plotbutton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotbutton.sizePolicy().hasHeightForWidth())
        self.plotbutton.setSizePolicy(sizePolicy)
        self.plotbutton.setMinimumSize(QtCore.QSize(75, 0))
        self.plotbutton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.plotbutton.setObjectName("plotbutton")
        self.horizontalLayout_2.addWidget(self.plotbutton)
        self.savefigpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.savefigpushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savefigpushButton.sizePolicy().hasHeightForWidth())
        self.savefigpushButton.setSizePolicy(sizePolicy)
        self.savefigpushButton.setMinimumSize(QtCore.QSize(85, 0))
        self.savefigpushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.savefigpushButton.setObjectName("savefigpushButton")
        self.horizontalLayout_2.addWidget(self.savefigpushButton)
        self.gridLayout_main.addLayout(self.horizontalLayout_2, 14, 0, 1, 1)
        self.horizontalLayout_hvLabels = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hvLabels.setObjectName("horizontalLayout_hvLabels")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setObjectName("label_x")
        self.horizontalLayout_hvLabels.addWidget(self.label_x)
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        self.label_y.setMaximumSize(QtCore.QSize(85, 16777215))
        self.label_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_y.setObjectName("label_y")
        self.horizontalLayout_hvLabels.addWidget(self.label_y)
        self.gridLayout_main.addLayout(self.horizontalLayout_hvLabels, 0, 0, 1, 1)
        self.horizontalLayout_cache = QtWidgets.QHBoxLayout()
        self.horizontalLayout_cache.setObjectName("horizontalLayout_cache")
        self.browsecacheline = QtWidgets.QLineEdit(self.centralwidget)
        self.browsecacheline.setObjectName("browsecacheline")
        self.horizontalLayout_cache.addWidget(self.browsecacheline)
        self.browsecachebutton = QtWidgets.QPushButton(self.centralwidget)
        self.browsecachebutton.setMinimumSize(QtCore.QSize(25, 0))
        self.browsecachebutton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.browsecachebutton.setObjectName("browsecachebutton")
        self.horizontalLayout_cache.addWidget(self.browsecachebutton)
        self.gridLayout_main.addLayout(self.horizontalLayout_cache, 3, 0, 1, 1)
        self.horizontalLayout_json = QtWidgets.QHBoxLayout()
        self.horizontalLayout_json.setObjectName("horizontalLayout_json")
        self.browsejsonline = QtWidgets.QLineEdit(self.centralwidget)
        self.browsejsonline.setObjectName("browsejsonline")
        self.horizontalLayout_json.addWidget(self.browsejsonline)
        self.browsejsonbutton = QtWidgets.QPushButton(self.centralwidget)
        self.browsejsonbutton.setMinimumSize(QtCore.QSize(25, 0))
        self.browsejsonbutton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.browsejsonbutton.setObjectName("browsejsonbutton")
        self.horizontalLayout_json.addWidget(self.browsejsonbutton)
        self.gridLayout_main.addLayout(self.horizontalLayout_json, 5, 0, 1, 1)
        self.horizontalLayout_hvinput = QtWidgets.QHBoxLayout()
        self.horizontalLayout_hvinput.setObjectName("horizontalLayout_hvinput")
        self.xline = QtWidgets.QLineEdit(self.centralwidget)
        self.xline.setMaximumSize(QtCore.QSize(85, 16777215))
        self.xline.setMaxLength(12)
        self.xline.setObjectName("xline")
        self.horizontalLayout_hvinput.addWidget(self.xline)
        self.yline = QtWidgets.QLineEdit(self.centralwidget)
        self.yline.setMaximumSize(QtCore.QSize(85, 16777215))
        self.yline.setMaxLength(12)
        self.yline.setObjectName("yline")
        self.horizontalLayout_hvinput.addWidget(self.yline)
        self.gridLayout_main.addLayout(self.horizontalLayout_hvinput, 1, 0, 1, 1)
        self.cache_label = QtWidgets.QLabel(self.centralwidget)
        self.cache_label.setObjectName("cache_label")
        self.gridLayout_main.addWidget(self.cache_label, 2, 0, 1, 1)
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setObjectName("output_label")
        self.gridLayout_main.addWidget(self.output_label, 6, 0, 1, 1)
        self.radioshp = QtWidgets.QRadioButton(self.centralwidget)
        self.radioshp.setChecked(True)
        self.radioshp.setAutoExclusive(False)
        self.radioshp.setObjectName("radioshp")
        self.gridLayout_main.addWidget(self.radioshp, 9, 0, 1, 1)
        self.json_label = QtWidgets.QLabel(self.centralwidget)
        self.json_label.setObjectName("json_label")
        self.gridLayout_main.addWidget(self.json_label, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_main.addItem(spacerItem1, 8, 0, 1, 1)
        self.horizontalLayout_plotsave = QtWidgets.QHBoxLayout()
        self.horizontalLayout_plotsave.setObjectName("horizontalLayout_plotsave")
        self.browseoutputline = QtWidgets.QLineEdit(self.centralwidget)
        self.browseoutputline.setObjectName("browseoutputline")
        self.horizontalLayout_plotsave.addWidget(self.browseoutputline)
        self.browseoutputbutton = QtWidgets.QPushButton(self.centralwidget)
        self.browseoutputbutton.setMinimumSize(QtCore.QSize(25, 0))
        self.browseoutputbutton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.browseoutputbutton.setObjectName("browseoutputbutton")
        self.horizontalLayout_plotsave.addWidget(self.browseoutputbutton)
        self.gridLayout_main.addLayout(self.horizontalLayout_plotsave, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_main.addItem(spacerItem2, 11, 0, 1, 1)
        self.listitems = QtWidgets.QListWidget(self.centralwidget)
        self.listitems.setAlternatingRowColors(False)
        self.listitems.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listitems.setObjectName("listitems")
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listitems.addItem(item)
        self.gridLayout_main.addWidget(self.listitems, 12, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_main, 0, 0, 1, 1)
        self.outputverticalLayout = QtWidgets.QVBoxLayout()
        self.outputverticalLayout.setObjectName("outputverticalLayout")
        self.modelresultsLabel = QtWidgets.QLabel(self.centralwidget)
        self.modelresultsLabel.setObjectName("modelresultsLabel")
        self.outputverticalLayout.addWidget(self.modelresultsLabel)
        self.plainTextEdit_results = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_results.setReadOnly(True)
        self.plainTextEdit_results.setObjectName("plainTextEdit_results")
        self.outputverticalLayout.addWidget(self.plainTextEdit_results)
        self.clickresultsLabel = QtWidgets.QLabel(self.centralwidget)
        self.clickresultsLabel.setObjectName("clickresultsLabel")
        self.outputverticalLayout.addWidget(self.clickresultsLabel)
        self.clicked_listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.clicked_listWidget.setAlternatingRowColors(True)
        self.clicked_listWidget.setObjectName("clicked_listWidget")
        self.outputverticalLayout.addWidget(self.clicked_listWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearpushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearpushButton.sizePolicy().hasHeightForWidth())
        self.clearpushButton.setSizePolicy(sizePolicy)
        self.clearpushButton.setMinimumSize(QtCore.QSize(75, 0))
        self.clearpushButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.clearpushButton.setObjectName("clearpushButton")
        self.horizontalLayout.addWidget(self.clearpushButton)
        self.exitbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitbutton.sizePolicy().hasHeightForWidth())
        self.exitbutton.setSizePolicy(sizePolicy)
        self.exitbutton.setMinimumSize(QtCore.QSize(75, 0))
        self.exitbutton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.exitbutton.setObjectName("exitbutton")
        self.horizontalLayout.addWidget(self.exitbutton)
        self.outputverticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.outputverticalLayout, 0, 1, 1, 1)
        TAP_Tool.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TAP_Tool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 21))
        self.menubar.setObjectName("menubar")
        TAP_Tool.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TAP_Tool)
        self.statusbar.setObjectName("statusbar")
        TAP_Tool.setStatusBar(self.statusbar)

        self.retranslateUi(TAP_Tool)
        QtCore.QMetaObject.connectSlotsByName(TAP_Tool)
        TAP_Tool.setTabOrder(self.xline, self.yline)
        TAP_Tool.setTabOrder(self.yline, self.browsecacheline)
        TAP_Tool.setTabOrder(self.browsecacheline, self.browsecachebutton)
        TAP_Tool.setTabOrder(self.browsecachebutton, self.browsejsonline)
        TAP_Tool.setTabOrder(self.browsejsonline, self.browsejsonbutton)
        TAP_Tool.setTabOrder(self.browsejsonbutton, self.browseoutputline)
        TAP_Tool.setTabOrder(self.browseoutputline, self.browseoutputbutton)
        TAP_Tool.setTabOrder(self.browseoutputbutton, self.radioshp)
        TAP_Tool.setTabOrder(self.radioshp, self.listitems)
        TAP_Tool.setTabOrder(self.listitems, self.plotbutton)
        TAP_Tool.setTabOrder(self.plotbutton, self.savefigpushButton)
        TAP_Tool.setTabOrder(self.savefigpushButton, self.plainTextEdit_results)
        TAP_Tool.setTabOrder(self.plainTextEdit_results, self.clearpushButton)
        TAP_Tool.setTabOrder(self.clearpushButton, self.exitbutton)

    def retranslateUi(self, TAP_Tool):
        _translate = QtCore.QCoreApplication.translate
        TAP_Tool.setWindowTitle(_translate("LCMAP_TAP", "Time Series Analysis and Plotting Tool"))
        self.plotbutton.setText(_translate("LCMAP_TAP", "Plot"))
        self.savefigpushButton.setText(_translate("LCMAP_TAP", "Save Figure"))
        self.label_x.setText(_translate("LCMAP_TAP", "X"))
        self.label_y.setText(_translate("LCMAP_TAP", "Y"))
        self.browsecachebutton.setText(_translate("LCMAP_TAP", "..."))
        self.browsejsonbutton.setText(_translate("LCMAP_TAP", "..."))
        self.cache_label.setText(_translate("LCMAP_TAP", "Full path to cache folder:"))
        self.output_label.setText(_translate("LCMAP_TAP", "Output directory to save plots:"))
        self.radioshp.setText(_translate("LCMAP_TAP", "Create Point Shapefile on Plot"))
        self.json_label.setText(_translate("LCMAP_TAP", "Full path to JSON folder:"))
        self.browseoutputbutton.setText(_translate("LCMAP_TAP", "..."))
        __sortingEnabled = self.listitems.isSortingEnabled()
        self.listitems.setSortingEnabled(False)
        item = self.listitems.item(0)
        item.setText(_translate("LCMAP_TAP", "All Bands and Indices"))
        item = self.listitems.item(1)
        item.setText(_translate("LCMAP_TAP", "All Bands"))
        item = self.listitems.item(2)
        item.setText(_translate("LCMAP_TAP", "All Indices"))
        item = self.listitems.item(3)
        item.setText(_translate("LCMAP_TAP", "Blue"))
        item = self.listitems.item(4)
        item.setText(_translate("LCMAP_TAP", "Green"))
        item = self.listitems.item(5)
        item.setText(_translate("LCMAP_TAP", "Red"))
        item = self.listitems.item(6)
        item.setText(_translate("LCMAP_TAP", "NIR"))
        item = self.listitems.item(7)
        item.setText(_translate("LCMAP_TAP", "SWIR-1"))
        item = self.listitems.item(8)
        item.setText(_translate("LCMAP_TAP", "SWIR-2"))
        item = self.listitems.item(9)
        item.setText(_translate("LCMAP_TAP", "Thermal"))
        item = self.listitems.item(10)
        item.setText(_translate("LCMAP_TAP", "NDVI"))
        item = self.listitems.item(11)
        item.setText(_translate("LCMAP_TAP", "MSAVI"))
        item = self.listitems.item(12)
        item.setText(_translate("LCMAP_TAP", "EVI"))
        item = self.listitems.item(13)
        item.setText(_translate("LCMAP_TAP", "SAVI"))
        item = self.listitems.item(14)
        item.setText(_translate("LCMAP_TAP", "NDMI"))
        item = self.listitems.item(15)
        item.setText(_translate("LCMAP_TAP", "NBR"))
        item = self.listitems.item(16)
        item.setText(_translate("LCMAP_TAP", "NBR-2"))
        self.listitems.setSortingEnabled(__sortingEnabled)
        self.modelresultsLabel.setText(_translate("LCMAP_TAP", "Model Results:"))
        self.clickresultsLabel.setText(_translate("LCMAP_TAP", "Selected Observations:"))
        self.clearpushButton.setText(_translate("LCMAP_TAP", "Clear"))
        self.exitbutton.setText(_translate("LCMAP_TAP", "Close"))

