# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chipviewer_main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import pkg_resources

class Ui_MainWindow_chipviewer(object):
    def setupUi(self, MainWindow_chipviewer):
        MainWindow_chipviewer.setObjectName("MainWindow_chipviewer")
        MainWindow_chipviewer.resize(646, 772)

        icon = QtGui.QIcon(QtGui.QPixmap(pkg_resources.resource_filename("lcmap_tap",
                                                                         "/".join(("Auxiliary", "icon.PNG")))))

        MainWindow_chipviewer.setWindowIcon(icon)

        self.Widget_central = QtWidgets.QWidget(MainWindow_chipviewer)
        self.Widget_central.setObjectName("Widget_central")
        self.gridLayout = QtWidgets.QGridLayout(self.Widget_central)
        self.gridLayout.setObjectName("gridLayout")
        self.ScrollArea_viewer = QtWidgets.QScrollArea(self.Widget_central)
        self.ScrollArea_viewer.setWidgetResizable(True)
        self.ScrollArea_viewer.setObjectName("ScrollArea_viewer")
        self.Widget_ScrollAreaContents = QtWidgets.QWidget()
        self.Widget_ScrollAreaContents.setGeometry(QtCore.QRect(0, 0, 626, 539))
        self.Widget_ScrollAreaContents.setObjectName("Widget_ScrollAreaContents")
        self.ScrollArea_viewer.setWidget(self.Widget_ScrollAreaContents)
        self.gridLayout.addWidget(self.ScrollArea_viewer, 0, 0, 1, 1)
        self.HBoxLayout_controls = QtWidgets.QHBoxLayout()
        self.HBoxLayout_controls.setObjectName("HBoxLayout_controls")
        self.VBoxLayout_enable = QtWidgets.QVBoxLayout()
        self.VBoxLayout_enable.setObjectName("VBoxLayout_enable")
        self.RadioButton_plot = QtWidgets.QRadioButton(self.Widget_central)
        self.RadioButton_plot.setObjectName("RadioButton_plot")
        self.VBoxLayout_enable.addWidget(self.RadioButton_plot)
        self.QLable_rightclick = QtWidgets.QLabel(self.Widget_central)
        self.QLable_rightclick.setObjectName("QLable_rightclick")
        self.VBoxLayout_enable.addWidget(self.QLable_rightclick, 0, QtCore.Qt.AlignLeft)
        self.QLabel_leftclick = QtWidgets.QLabel(self.Widget_central)
        self.QLabel_leftclick.setObjectName("QLabel_leftclick")
        self.VBoxLayout_enable.addWidget(self.QLabel_leftclick, 0, QtCore.Qt.AlignLeft)
        self.QLabel_zoom = QtWidgets.QLabel(self.Widget_central)
        self.QLabel_zoom.setObjectName("QLabel_zoom")
        self.VBoxLayout_enable.addWidget(self.QLabel_zoom, 0, QtCore.Qt.AlignLeft)
        self.HBoxLayout_controls.addLayout(self.VBoxLayout_enable)
        self.VBoxLayout_update = QtWidgets.QVBoxLayout()
        self.VBoxLayout_update.setObjectName("VBoxLayout_update")
        self.HBoxLayout_percents = QtWidgets.QHBoxLayout()
        self.HBoxLayout_percents.setObjectName("HBoxLayout_percents")
        self.VBoxLayout_lower = QtWidgets.QVBoxLayout()
        self.VBoxLayout_lower.setObjectName("VBoxLayout_lower")
        self.Label_lower = QtWidgets.QLabel(self.Widget_central)
        self.Label_lower.setObjectName("Label_lower")
        self.VBoxLayout_lower.addWidget(self.Label_lower, 0, QtCore.Qt.AlignHCenter)
        self.LineEdit_lower = QtWidgets.QLineEdit(self.Widget_central)
        self.LineEdit_lower.setMaximumSize(QtCore.QSize(40, 16777215))
        self.LineEdit_lower.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LineEdit_lower.setMaxLength(6)
        self.LineEdit_lower.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LineEdit_lower.setObjectName("LineEdit_lower")
        self.VBoxLayout_lower.addWidget(self.LineEdit_lower, 0, QtCore.Qt.AlignHCenter)
        self.HBoxLayout_percents.addLayout(self.VBoxLayout_lower)
        self.VBoxLayout_upper = QtWidgets.QVBoxLayout()
        self.VBoxLayout_upper.setObjectName("VBoxLayout_upper")
        self.Label_upper = QtWidgets.QLabel(self.Widget_central)
        self.Label_upper.setObjectName("Label_upper")
        self.VBoxLayout_upper.addWidget(self.Label_upper, 0, QtCore.Qt.AlignHCenter)
        self.LineEdit_upper = QtWidgets.QLineEdit(self.Widget_central)
        self.LineEdit_upper.setMaximumSize(QtCore.QSize(40, 16777215))
        self.LineEdit_upper.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LineEdit_upper.setMaxLength(6)
        self.LineEdit_upper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LineEdit_upper.setObjectName("LineEdit_upper")
        self.VBoxLayout_upper.addWidget(self.LineEdit_upper, 0, QtCore.Qt.AlignHCenter)
        self.HBoxLayout_percents.addLayout(self.VBoxLayout_upper)
        self.VBoxLayout_update.addLayout(self.HBoxLayout_percents)
        self.HBoxLayout_red = QtWidgets.QHBoxLayout()
        self.HBoxLayout_red.setObjectName("HBoxLayout_red")
        self.VBoxLayout_red_label = QtWidgets.QVBoxLayout()
        self.VBoxLayout_red_label.setObjectName("VBoxLayout_red_label")
        self.Label_red = QtWidgets.QLabel(self.Widget_central)
        self.Label_red.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Label_red.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_red.setObjectName("Label_red")
        self.VBoxLayout_red_label.addWidget(self.Label_red)
        self.HBoxLayout_red.addLayout(self.VBoxLayout_red_label)
        self.VBoxLayout_red_combo = QtWidgets.QVBoxLayout()
        self.VBoxLayout_red_combo.setObjectName("VBoxLayout_red_combo")
        self.ComboBox_red = QtWidgets.QComboBox(self.Widget_central)
        self.ComboBox_red.setObjectName("ComboBox_red")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.setItemText(0, "")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.ComboBox_red.addItem("")
        self.VBoxLayout_red_combo.addWidget(self.ComboBox_red)
        self.HBoxLayout_red.addLayout(self.VBoxLayout_red_combo)
        self.VBoxLayout_update.addLayout(self.HBoxLayout_red)
        self.HBoxLayout_green = QtWidgets.QHBoxLayout()
        self.HBoxLayout_green.setObjectName("HBoxLayout_green")
        self.VBoxLayout_green_label = QtWidgets.QVBoxLayout()
        self.VBoxLayout_green_label.setObjectName("VBoxLayout_green_label")
        self.Label_green = QtWidgets.QLabel(self.Widget_central)
        self.Label_green.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_green.setObjectName("Label_green")
        self.VBoxLayout_green_label.addWidget(self.Label_green)
        self.HBoxLayout_green.addLayout(self.VBoxLayout_green_label)
        self.VBoxLayout_green_combo = QtWidgets.QVBoxLayout()
        self.VBoxLayout_green_combo.setObjectName("VBoxLayout_green_combo")
        self.ComboBox_green = QtWidgets.QComboBox(self.Widget_central)
        self.ComboBox_green.setObjectName("ComboBox_green")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.setItemText(0, "")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.ComboBox_green.addItem("")
        self.VBoxLayout_green_combo.addWidget(self.ComboBox_green)
        self.HBoxLayout_green.addLayout(self.VBoxLayout_green_combo)
        self.VBoxLayout_update.addLayout(self.HBoxLayout_green)
        self.HBoxLayout_blue = QtWidgets.QHBoxLayout()
        self.HBoxLayout_blue.setObjectName("HBoxLayout_blue")
        self.VBoxLayout_blue_label = QtWidgets.QVBoxLayout()
        self.VBoxLayout_blue_label.setObjectName("VBoxLayout_blue_label")
        self.Label_blue = QtWidgets.QLabel(self.Widget_central)
        self.Label_blue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_blue.setObjectName("Label_blue")
        self.VBoxLayout_blue_label.addWidget(self.Label_blue)
        self.HBoxLayout_blue.addLayout(self.VBoxLayout_blue_label)
        self.VBoxLayout_blue_combo = QtWidgets.QVBoxLayout()
        self.VBoxLayout_blue_combo.setObjectName("VBoxLayout_blue_combo")
        self.ComboBox_blue = QtWidgets.QComboBox(self.Widget_central)
        self.ComboBox_blue.setObjectName("ComboBox_blue")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.setItemText(0, "")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.ComboBox_blue.addItem("")
        self.VBoxLayout_blue_combo.addWidget(self.ComboBox_blue)
        self.HBoxLayout_blue.addLayout(self.VBoxLayout_blue_combo)
        self.VBoxLayout_update.addLayout(self.HBoxLayout_blue)
        self.PushButton_update = QtWidgets.QPushButton(self.Widget_central)
        self.PushButton_update.setMinimumSize(QtCore.QSize(100, 0))
        self.PushButton_update.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PushButton_update.setObjectName("PushButton_update")
        self.VBoxLayout_update.addWidget(self.PushButton_update, 0, QtCore.Qt.AlignHCenter)
        self.HBoxLayout_controls.addLayout(self.VBoxLayout_update)
        self.VBoxLayout_zoom = QtWidgets.QVBoxLayout()
        self.VBoxLayout_zoom.setObjectName("VBoxLayout_zoom")
        self.PushButton_zoom = QtWidgets.QPushButton(self.Widget_central)
        self.PushButton_zoom.setMinimumSize(QtCore.QSize(100, 0))
        self.PushButton_zoom.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PushButton_zoom.setObjectName("PushButton_zoom")
        self.VBoxLayout_zoom.addWidget(self.PushButton_zoom, 0, QtCore.Qt.AlignHCenter)
        self.PushButton_save = QtWidgets.QPushButton(self.Widget_central)
        self.PushButton_save.setMinimumSize(QtCore.QSize(100, 0))
        self.PushButton_save.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PushButton_save.setObjectName("PushButton_save")
        self.VBoxLayout_zoom.addWidget(self.PushButton_save, 0, QtCore.Qt.AlignHCenter)
        self.HBoxLayout_controls.addLayout(self.VBoxLayout_zoom)
        self.gridLayout.addLayout(self.HBoxLayout_controls, 1, 0, 1, 1)
        MainWindow_chipviewer.setCentralWidget(self.Widget_central)
        self.menubar = QtWidgets.QMenuBar(MainWindow_chipviewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_chipviewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_chipviewer)
        self.statusbar.setObjectName("statusbar")
        MainWindow_chipviewer.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_chipviewer)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_chipviewer)

    def retranslateUi(self, MainWindow_chipviewer):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_chipviewer.setWindowTitle(_translate("MainWindow_chipviewer", "ARD Viewer"))
        self.RadioButton_plot.setText(_translate("MainWindow_chipviewer", "Enable Plot on Click"))
        self.QLable_rightclick.setText(_translate("MainWindow_chipviewer", "Right Click - Toggle Pan On/Off"))
        self.QLabel_leftclick.setText(_translate("MainWindow_chipviewer", "Left Click - Return Point Location"))
        self.QLabel_zoom.setText(_translate("MainWindow_chipviewer", "Wheel  - Zoom In/Out"))
        self.Label_lower.setText(_translate("MainWindow_chipviewer", "Lower"))
        self.LineEdit_lower.setText(_translate("MainWindow_chipviewer", "1"))
        self.Label_upper.setText(_translate("MainWindow_chipviewer", "Upper"))
        self.LineEdit_upper.setText(_translate("MainWindow_chipviewer", "99"))
        self.Label_red.setText(_translate("MainWindow_chipviewer", "Red Channel: "))
        self.ComboBox_red.setItemText(1, _translate("MainWindow_chipviewer", "Blue"))
        self.ComboBox_red.setItemText(2, _translate("MainWindow_chipviewer", "Green"))
        self.ComboBox_red.setItemText(3, _translate("MainWindow_chipviewer", "Red"))
        self.ComboBox_red.setItemText(4, _translate("MainWindow_chipviewer", "NIR"))
        self.ComboBox_red.setItemText(5, _translate("MainWindow_chipviewer", "SWIR-1"))
        self.ComboBox_red.setItemText(6, _translate("MainWindow_chipviewer", "SWIR-2"))
        self.ComboBox_red.setItemText(7, _translate("MainWindow_chipviewer", "Thermal"))
        self.ComboBox_red.setItemText(8, _translate("MainWindow_chipviewer", "NDVI"))
        self.ComboBox_red.setItemText(9, _translate("MainWindow_chipviewer", "MSAVI"))
        self.ComboBox_red.setItemText(10, _translate("MainWindow_chipviewer", "SAVI"))
        self.ComboBox_red.setItemText(11, _translate("MainWindow_chipviewer", "EVI"))
        self.ComboBox_red.setItemText(12, _translate("MainWindow_chipviewer", "NDMI"))
        self.ComboBox_red.setItemText(13, _translate("MainWindow_chipviewer", "NBR-1"))
        self.ComboBox_red.setItemText(14, _translate("MainWindow_chipviewer", "NBR-2"))
        self.Label_green.setText(_translate("MainWindow_chipviewer", "Green Channel: "))
        self.ComboBox_green.setItemText(1, _translate("MainWindow_chipviewer", "Blue"))
        self.ComboBox_green.setItemText(2, _translate("MainWindow_chipviewer", "Green"))
        self.ComboBox_green.setItemText(3, _translate("MainWindow_chipviewer", "Red"))
        self.ComboBox_green.setItemText(4, _translate("MainWindow_chipviewer", "NIR"))
        self.ComboBox_green.setItemText(5, _translate("MainWindow_chipviewer", "SWIR-1"))
        self.ComboBox_green.setItemText(6, _translate("MainWindow_chipviewer", "SWIR-2"))
        self.ComboBox_green.setItemText(7, _translate("MainWindow_chipviewer", "Thermal"))
        self.ComboBox_green.setItemText(8, _translate("MainWindow_chipviewer", "NDVI"))
        self.ComboBox_green.setItemText(9, _translate("MainWindow_chipviewer", "MSAVI"))
        self.ComboBox_green.setItemText(10, _translate("MainWindow_chipviewer", "SAVI"))
        self.ComboBox_green.setItemText(11, _translate("MainWindow_chipviewer", "EVI"))
        self.ComboBox_green.setItemText(12, _translate("MainWindow_chipviewer", "NDMI"))
        self.ComboBox_green.setItemText(13, _translate("MainWindow_chipviewer", "NBR-1"))
        self.ComboBox_green.setItemText(14, _translate("MainWindow_chipviewer", "NBR-2"))
        self.Label_blue.setText(_translate("MainWindow_chipviewer", "Blue Channel: "))
        self.ComboBox_blue.setItemText(1, _translate("MainWindow_chipviewer", "Blue"))
        self.ComboBox_blue.setItemText(2, _translate("MainWindow_chipviewer", "Green"))
        self.ComboBox_blue.setItemText(3, _translate("MainWindow_chipviewer", "Red"))
        self.ComboBox_blue.setItemText(4, _translate("MainWindow_chipviewer", "NIR"))
        self.ComboBox_blue.setItemText(5, _translate("MainWindow_chipviewer", "SWIR-1"))
        self.ComboBox_blue.setItemText(6, _translate("MainWindow_chipviewer", "SWIR-2"))
        self.ComboBox_blue.setItemText(7, _translate("MainWindow_chipviewer", "Thermal"))
        self.ComboBox_blue.setItemText(8, _translate("MainWindow_chipviewer", "NDVI"))
        self.ComboBox_blue.setItemText(9, _translate("MainWindow_chipviewer", "MSAVI"))
        self.ComboBox_blue.setItemText(10, _translate("MainWindow_chipviewer", "SAVI"))
        self.ComboBox_blue.setItemText(11, _translate("MainWindow_chipviewer", "EVI"))
        self.ComboBox_blue.setItemText(12, _translate("MainWindow_chipviewer", "NDMI"))
        self.ComboBox_blue.setItemText(13, _translate("MainWindow_chipviewer", "NBR-1"))
        self.ComboBox_blue.setItemText(14, _translate("MainWindow_chipviewer", "NBR-2"))
        self.PushButton_update.setText(_translate("MainWindow_chipviewer", "Update"))
        self.PushButton_zoom.setText(_translate("MainWindow_chipviewer", "Zoom to Point"))
        self.PushButton_save.setText(_translate("MainWindow_chipviewer", "Save Figure"))

