# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_ARD_VIEWER.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ARDViewer(object):
    def setupUi(self, ARDViewer):
        ARDViewer.setObjectName("ARDViewer")
        ARDViewer.resize(653, 719)
        self.centralwidget = QtWidgets.QWidget(ARDViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 633, 574))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioPlot = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPlot.setObjectName("radioPlot")
        self.verticalLayout_3.addWidget(self.radioPlot)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignLeft)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setMinimumSize(QtCore.QSize(100, 0))
        self.update_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.update_button.setObjectName("update_button")
        self.verticalLayout_2.addWidget(self.update_button, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.zoom_button = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_button.setMinimumSize(QtCore.QSize(100, 0))
        self.zoom_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.zoom_button.setObjectName("zoom_button")
        self.verticalLayout.addWidget(self.zoom_button, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        ARDViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ARDViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 21))
        self.menubar.setObjectName("menubar")
        self.menuImage = QtWidgets.QMenu(self.menubar)
        self.menuImage.setObjectName("menuImage")
        self.menuR = QtWidgets.QMenu(self.menuImage)
        self.menuR.setObjectName("menuR")
        self.menuG = QtWidgets.QMenu(self.menuImage)
        self.menuG.setObjectName("menuG")
        self.menuB = QtWidgets.QMenu(self.menuImage)
        self.menuB.setObjectName("menuB")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuIndicies = QtWidgets.QMenu(self.menubar)
        self.menuIndicies.setObjectName("menuIndicies")
        ARDViewer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ARDViewer)
        self.statusbar.setObjectName("statusbar")
        ARDViewer.setStatusBar(self.statusbar)
        self.actionBand_1 = QtWidgets.QAction(ARDViewer)
        self.actionBand_1.setCheckable(True)
        self.actionBand_1.setObjectName("actionBand_1")
        self.actionBand_2 = QtWidgets.QAction(ARDViewer)
        self.actionBand_2.setCheckable(True)
        self.actionBand_2.setObjectName("actionBand_2")
        self.actionBand_3 = QtWidgets.QAction(ARDViewer)
        self.actionBand_3.setCheckable(True)
        self.actionBand_3.setObjectName("actionBand_3")
        self.actionBand_4 = QtWidgets.QAction(ARDViewer)
        self.actionBand_4.setCheckable(True)
        self.actionBand_4.setObjectName("actionBand_4")
        self.actionBand_5 = QtWidgets.QAction(ARDViewer)
        self.actionBand_5.setCheckable(True)
        self.actionBand_5.setObjectName("actionBand_5")
        self.actionBand_6 = QtWidgets.QAction(ARDViewer)
        self.actionBand_6.setCheckable(True)
        self.actionBand_6.setObjectName("actionBand_6")
        self.actionBand_7 = QtWidgets.QAction(ARDViewer)
        self.actionBand_7.setCheckable(True)
        self.actionBand_7.setObjectName("actionBand_7")
        self.actionBand_8 = QtWidgets.QAction(ARDViewer)
        self.actionBand_8.setCheckable(True)
        self.actionBand_8.setObjectName("actionBand_8")
        self.actionBand_9 = QtWidgets.QAction(ARDViewer)
        self.actionBand_9.setCheckable(True)
        self.actionBand_9.setObjectName("actionBand_9")
        self.actionBand_10 = QtWidgets.QAction(ARDViewer)
        self.actionBand_10.setCheckable(True)
        self.actionBand_10.setObjectName("actionBand_10")
        self.actionBand_11 = QtWidgets.QAction(ARDViewer)
        self.actionBand_11.setCheckable(True)
        self.actionBand_11.setObjectName("actionBand_11")
        self.actionBand_12 = QtWidgets.QAction(ARDViewer)
        self.actionBand_12.setCheckable(True)
        self.actionBand_12.setObjectName("actionBand_12")
        self.actionBand_13 = QtWidgets.QAction(ARDViewer)
        self.actionBand_13.setCheckable(True)
        self.actionBand_13.setObjectName("actionBand_13")
        self.actionBand_14 = QtWidgets.QAction(ARDViewer)
        self.actionBand_14.setCheckable(True)
        self.actionBand_14.setObjectName("actionBand_14")
        self.actionBand_15 = QtWidgets.QAction(ARDViewer)
        self.actionBand_15.setCheckable(True)
        self.actionBand_15.setObjectName("actionBand_15")
        self.actionBand_16 = QtWidgets.QAction(ARDViewer)
        self.actionBand_16.setCheckable(True)
        self.actionBand_16.setObjectName("actionBand_16")
        self.actionBand_17 = QtWidgets.QAction(ARDViewer)
        self.actionBand_17.setCheckable(True)
        self.actionBand_17.setObjectName("actionBand_17")
        self.actionBand_18 = QtWidgets.QAction(ARDViewer)
        self.actionBand_18.setCheckable(True)
        self.actionBand_18.setObjectName("actionBand_18")
        self.actionNDVI = QtWidgets.QAction(ARDViewer)
        self.actionNDVI.setObjectName("actionNDVI")
        self.action100x100 = QtWidgets.QAction(ARDViewer)
        self.action100x100.setCheckable(True)
        self.action100x100.setObjectName("action100x100")
        self.action250x250 = QtWidgets.QAction(ARDViewer)
        self.action250x250.setCheckable(True)
        self.action250x250.setObjectName("action250x250")
        self.action500x500 = QtWidgets.QAction(ARDViewer)
        self.action500x500.setCheckable(True)
        self.action500x500.setObjectName("action500x500")
        self.action1000x1000 = QtWidgets.QAction(ARDViewer)
        self.action1000x1000.setCheckable(True)
        self.action1000x1000.setObjectName("action1000x1000")
        self.actionFull = QtWidgets.QAction(ARDViewer)
        self.actionFull.setCheckable(True)
        self.actionFull.setObjectName("actionFull")
        self.actionUpdateBands = QtWidgets.QAction(ARDViewer)
        self.actionUpdateBands.setObjectName("actionUpdateBands")
        self.actionSave_Image = QtWidgets.QAction(ARDViewer)
        self.actionSave_Image.setObjectName("actionSave_Image")
        self.actionExit = QtWidgets.QAction(ARDViewer)
        self.actionExit.setObjectName("actionExit")
        self.actionMSAVI = QtWidgets.QAction(ARDViewer)
        self.actionMSAVI.setObjectName("actionMSAVI")
        self.actionSAVI = QtWidgets.QAction(ARDViewer)
        self.actionSAVI.setObjectName("actionSAVI")
        self.actionNDMI = QtWidgets.QAction(ARDViewer)
        self.actionNDMI.setObjectName("actionNDMI")
        self.actionNBR = QtWidgets.QAction(ARDViewer)
        self.actionNBR.setObjectName("actionNBR")
        self.actionEVI = QtWidgets.QAction(ARDViewer)
        self.actionEVI.setObjectName("actionEVI")
        self.actionNBR_2 = QtWidgets.QAction(ARDViewer)
        self.actionNBR_2.setObjectName("actionNBR_2")
        self.actionTC = QtWidgets.QAction(ARDViewer)
        self.actionTC.setObjectName("actionTC")
        self.menuR.addAction(self.actionBand_1)
        self.menuR.addAction(self.actionBand_2)
        self.menuR.addAction(self.actionBand_3)
        self.menuR.addAction(self.actionBand_4)
        self.menuR.addAction(self.actionBand_5)
        self.menuR.addAction(self.actionBand_6)
        self.menuG.addAction(self.actionBand_7)
        self.menuG.addAction(self.actionBand_8)
        self.menuG.addAction(self.actionBand_9)
        self.menuG.addAction(self.actionBand_10)
        self.menuG.addAction(self.actionBand_11)
        self.menuG.addAction(self.actionBand_12)
        self.menuB.addAction(self.actionBand_13)
        self.menuB.addAction(self.actionBand_14)
        self.menuB.addAction(self.actionBand_15)
        self.menuB.addAction(self.actionBand_16)
        self.menuB.addAction(self.actionBand_17)
        self.menuB.addAction(self.actionBand_18)
        self.menuImage.addAction(self.menuR.menuAction())
        self.menuImage.addAction(self.menuG.menuAction())
        self.menuImage.addAction(self.menuB.menuAction())
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionExit)
        self.menuIndicies.addAction(self.actionNDVI)
        self.menuIndicies.addAction(self.actionMSAVI)
        self.menuIndicies.addAction(self.actionSAVI)
        self.menuIndicies.addAction(self.actionEVI)
        self.menuIndicies.addAction(self.actionNDMI)
        self.menuIndicies.addAction(self.actionNBR)
        self.menuIndicies.addAction(self.actionNBR_2)
        self.menuIndicies.addAction(self.actionTC)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuIndicies.menuAction())

        self.retranslateUi(ARDViewer)
        QtCore.QMetaObject.connectSlotsByName(ARDViewer)

    def retranslateUi(self, ARDViewer):
        _translate = QtCore.QCoreApplication.translate
        ARDViewer.setWindowTitle(_translate("ARDViewer", "ARD Viewer"))
        self.radioPlot.setText(_translate("ARDViewer", "Enable Plot on Click"))
        self.label.setText(_translate("ARDViewer", "Right Click - Toggle Pan On/Off"))
        self.label_2.setText(_translate("ARDViewer", "Left Click - Return Point Location"))
        self.label_4.setText(_translate("ARDViewer", "Wheel  - Zoom In/Out"))
        self.update_button.setText(_translate("ARDViewer", "Update"))
        self.zoom_button.setText(_translate("ARDViewer", "Zoom to Point"))
        self.menuImage.setTitle(_translate("ARDViewer", "Bands"))
        self.menuR.setTitle(_translate("ARDViewer", "R"))
        self.menuG.setTitle(_translate("ARDViewer", "G"))
        self.menuB.setTitle(_translate("ARDViewer", "B"))
        self.menuFile.setTitle(_translate("ARDViewer", "File"))
        self.menuIndicies.setTitle(_translate("ARDViewer", "Indicies"))
        self.actionBand_1.setText(_translate("ARDViewer", "Band 1"))
        self.actionBand_2.setText(_translate("ARDViewer", "Band 2"))
        self.actionBand_3.setText(_translate("ARDViewer", "Band 3"))
        self.actionBand_4.setText(_translate("ARDViewer", "Band 4"))
        self.actionBand_5.setText(_translate("ARDViewer", "Band 5"))
        self.actionBand_6.setText(_translate("ARDViewer", "Band 6"))
        self.actionBand_7.setText(_translate("ARDViewer", "Band 1"))
        self.actionBand_8.setText(_translate("ARDViewer", "Band 2"))
        self.actionBand_9.setText(_translate("ARDViewer", "Band 3"))
        self.actionBand_10.setText(_translate("ARDViewer", "Band 4"))
        self.actionBand_11.setText(_translate("ARDViewer", "Band 5"))
        self.actionBand_12.setText(_translate("ARDViewer", "Band 6"))
        self.actionBand_13.setText(_translate("ARDViewer", "Band 1"))
        self.actionBand_14.setText(_translate("ARDViewer", "Band 2"))
        self.actionBand_15.setText(_translate("ARDViewer", "Band 3"))
        self.actionBand_16.setText(_translate("ARDViewer", "Band 4"))
        self.actionBand_17.setText(_translate("ARDViewer", "Band 5"))
        self.actionBand_18.setText(_translate("ARDViewer", "Band 6"))
        self.action100x100.setText(_translate("ARDViewer", "100x100"))
        self.action250x250.setText(_translate("ARDViewer", "250x250"))
        self.action500x500.setText(_translate("ARDViewer", "500x500"))
        self.action1000x1000.setText(_translate("ARDViewer", "1000x1000"))
        self.actionFull.setText(_translate("ARDViewer", "Full"))
        self.actionUpdateBands.setText(_translate("ARDViewer", "Update"))
        self.actionSave_Image.setText(_translate("ARDViewer", "Save Image"))
        self.actionExit.setText(_translate("ARDViewer", "Exit"))
        self.actionNDVI.setText(_translate("ARDViewer", "NDVI"))
        self.actionMSAVI.setText(_translate("ARDViewer", "MSAVI"))
        self.actionSAVI.setText(_translate("ARDViewer", "SAVI"))
        self.actionNDMI.setText(_translate("ARDViewer", "NDMI"))
        self.actionNBR.setText(_translate("ARDViewer", "NBR"))
        self.actionEVI.setText(_translate("ARDViewer", "EVI"))
        self.actionNBR_2.setText(_translate("ARDViewer", "NBR-2"))
        self.actionTC.setText(_translate("ARDViewer", "TC"))
